=== farao-community/ce-merging-server/src/main/resources/xsd/feasibility-range-document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="bci" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="bci">
  <xs:element name="FeasibilityRangeDocument">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:DocumentIdentification"/>
        <xs:element ref="ns1:DocumentVersion"/>
        <xs:element ref="ns1:DocumentType"/>
        <xs:element ref="ns1:SenderIdentification"/>
        <xs:element ref="ns1:SenderRole"/>
        <xs:element ref="ns1:ReceiverIdentification"/>
        <xs:element ref="ns1:ReceiverRole"/>
        <xs:element ref="ns1:CreationDateTime"/>
        <xs:element ref="ns1:PublicationTimeInterval"/>
        <xs:element ref="ns1:Constraints"/>
      </xs:sequence>
      <xs:attribute name="DtdRelease" use="required" type="xs:integer"/>
      <xs:attribute name="DtdVersion" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentIdentification">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentVersion">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentType">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SenderIdentification">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SenderRole">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ReceiverIdentification">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ReceiverRole">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CreationDateTime">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="PublicationTimeInterval">
    <xs:complexType>
      <xs:attribute name="v" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Constraints">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:FeasibilityRangeConstraint"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="FeasibilityRangeConstraint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:Area"/>
        <xs:element ref="ns1:Min"/>
        <xs:element ref="ns1:Max"/>
        <xs:element ref="ns1:Type"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="Area">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Min">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Max">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Type">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== farao-community/ce-merging-server/src/test/resources/bci/bciFeasibilityRange.xml
<?xml version='1.0' encoding='UTF-8'?>
<FeasibilityRangeDocument DtdRelease="0" DtdVersion="1" xmlns="bci" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="feasibility-range-document.xsd">
  <DocumentIdentification v="FeasibilityRange-for-Core-Bci" />
  <DocumentVersion v="1" />
  <DocumentType v="A45" />
  <SenderIdentification codingScheme="A01" v="WHO_MERGES" />
  <SenderRole v="A04"/>
  <ReceiverIdentification codingScheme="A01" v="GRID_OPERATOR"/>
  <ReceiverRole v="A36"/>
  <CreationDateTime v="2019-10-08T18:51:00Z"/>
  <PublicationTimeInterval v="2015-03-31T22:00Z/2015-04-01T22:00Z"/>
  <Constraints>
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER11_EIC"/>
		<Min v="-1000"/>
		<Max v="1000"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER2_EIC"/>
		<Min v="-200"/>
		<Max v="200"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER8_EIC"/>
		<Min v="-5000"/>
		<Max v="5000"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER13_EIC"/>
		<Min v="-300"/>
		<Max v="300"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>       
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER12_EIC"/>
		<Min v="-2000"/>
		<Max v="2000"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>       
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER10_EIC"/>
		<Min v="-150"/>
		<Max v="150"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>       
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER3_EIC"/>
		<Min v="-500"/>
		<Max v="500"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>    
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER26_EIC"/>
		<Min v="-300"/>
		<Max v="1000"/>
		<Type v="ABSOLUTE"/>
	</FeasibilityRangeConstraint>  
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER1_EIC"/>
		<Min v="-4000"/>
		<Max v="3000"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>  
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER5_EIC"/>
		<Min v="-100"/>
		<Max v="100"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>  
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER23_EIC"/>
		<Min v="-200"/>
		<Max v="200"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>  
	<FeasibilityRangeConstraint>
		<Area codingScheme="A01" v="AREA_NUMBER25_EIC"/>
		<Min v="-1500"/>
		<Max v="1500"/>
		<Type v="RELATIVE"/>
	</FeasibilityRangeConstraint>  
  </Constraints>
</FeasibilityRangeDocument>
