=== farao-community/ce-merging-server/src/main/resources/xsd/flowbasedexternalconstraintdocument-06.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns1="flowbased">
  <xs:element name="FlowBasedExternalConstraintDocument">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:DocumentIdentification"/>
        <xs:element ref="ns1:DocumentVersion"/>
        <xs:element ref="ns1:DocumentType"/>
        <xs:element ref="ns1:ProcessType"/>
        <xs:element ref="ns1:SenderIdentification"/>
        <xs:element ref="ns1:SenderRole"/>
        <xs:element ref="ns1:ReceiverIdentification"/>
        <xs:element ref="ns1:ReceiverRole"/>
        <xs:element ref="ns1:CreationDateTime"/>
        <xs:element ref="ns1:ExternalConstraintTimeInterval"/>
        <xs:element ref="ns1:Domain"/>
        <xs:element ref="ns1:constraints"/>
      </xs:sequence>
      <xs:attribute name="DtdRelease" use="required" type="xs:integer"/>
      <xs:attribute name="DtdVersion" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentIdentification">
    <xs:complexType>
      <xs:attribute name="v" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentVersion">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="DocumentType">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ProcessType">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SenderIdentification">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="SenderRole">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ReceiverIdentification">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ReceiverRole">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="CreationDateTime">
    <xs:complexType>
      <xs:attribute name="v" use="required" type="xs:dateTime"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="ExternalConstraintTimeInterval">
    <xs:complexType>
      <xs:attribute name="v" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Domain">
    <xs:complexType>
      <xs:attribute name="codingScheme" use="required" type="xs:NCName"/>
      <xs:attribute name="v" use="required" type="xs:NMTOKEN"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="constraints">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="ns1:netPositionConstraint"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="netPositionConstraint">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="ns1:timeInterval"/>
        <xs:element ref="ns1:tsoOrigin"/>
      </xs:sequence>
      <xs:attribute name="direction" use="required" type="xs:NCName"/>
      <xs:attribute name="hub" use="required" type="xs:NCName"/>
      <xs:attribute name="id" type="xs:string"/>
      <xs:attribute name="name" use="required" type="xs:NCName"/>
      <xs:attribute name="type" use="required" type="xs:NCName"/>
      <xs:attribute name="value" use="required" type="xs:integer"/>
      <xs:attribute name="version" use="required" type="xs:integer"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="timeInterval">
    <xs:complexType>
      <xs:attribute name="v" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="tsoOrigin" type="xs:NCName"/>
</xs:schema>

=== farao-community/ce-merging-server/src/test/resources/bci/F229-MergedECs_v01.xml
<?xml version='1.0' encoding='UTF-8'?>
<FlowBasedExternalConstraintDocument DtdRelease="4" DtdVersion="0" xmlns="flowbased" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="flowbasedexternalconstraintdocument-06.xsd">
  <DocumentIdentification v="17XTSO-CS------W-20190302-F229v1" />
  <DocumentVersion v="1" />
  <DocumentType v="Z06" />
  <ProcessType v="A01" />
  <SenderIdentification codingScheme="A01" v="GRID_OPERATOR" />
  <SenderRole v="A36" />
  <ReceiverIdentification codingScheme="A01" v="10X1001C--00003T" />
  <ReceiverRole v="A44" />
  <CreationDateTime v="2019-08-15T15:18:54Z" />
  <ExternalConstraintTimeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z" />
  <Domain codingScheme="A01" v="10YDOM-REGION-1V" />
  <constraints>
        <netPositionConstraint direction="EXPORT" hub="N12" id="2" name="N12_export" type="ABSOLUTE" value="9999" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N12</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="N12" id="1" name="N12_import" type="ABSOLUTE" value="0" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N12</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="N25" id="4" name="N25_export" type="ABSOLUTE" value="11285" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N25</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="N25" id="3" name="N25_import" type="ABSOLUTE" value="0" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N25</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="EXPORT" hub="N26" id="6" name="N26_export" type="ABSOLUTE" value="11285" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N26</tsoOrigin>
        </netPositionConstraint>
        <netPositionConstraint direction="IMPORT" hub="N26" id="5" name="N26_import" type="ABSOLUTE" value="0" version="0">
          <timeInterval v="2019-03-01T23:00Z/2019-03-02T23:00Z"/>
          <tsoOrigin>N26</tsoOrigin>
        </netPositionConstraint>
  </constraints>
</FlowBasedExternalConstraintDocument>
