=== farao-community/ce-merging-server/src/main/resources/xsd/glsk_fix/gsk-document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by baracchini (RTE) -->
<xsd:schema xmlns:ecc="etso-core-cmpts.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:import namespace="etso-core-cmpts.xsd" schemaLocation="etso-core-cmpts.xsd"/>
	<xsd:element name="GSKDocument">
		<xsd:complexType>
			<xsd:annotation>
				<xsd:documentation/>
			</xsd:annotation>
			<xsd:sequence>
				<xsd:element name="DocumentIdentification" type="ecc:IdentificationType"/>
				<xsd:element name="DocumentVersion" type="ecc:VersionType"/>
				<xsd:element name="DocumentType" type="ecc:MessageType"/>
				<xsd:element name="ProcessType" type="ecc:ProcessType"/>
				<xsd:element name="SenderIdentification" type="ecc:PartyType"/>
				<xsd:element name="SenderRole" type="ecc:RoleType"/>
				<xsd:element name="ReceiverIdentification" type="ecc:PartyType"/>
				<xsd:element name="ReceiverRole" type="ecc:RoleType"/>
				<xsd:element name="CreationDateTime" type="ecc:MessageDateTimeType"/>
				<xsd:element name="GSKTimeInterval" type="ecc:TimeIntervalType"/>
				<xsd:element name="Domain" type="ecc:AreaType"/>
				<xsd:element name="GSKSeries" type="GSKSeries_Type" minOccurs="0" maxOccurs="unbounded"/>
				<xsd:element name="Reason" type="Reason_Type" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:sequence>
			<xsd:attribute name="DtdRelease" type="xsd:string" use="optional"/>
			<xsd:attribute name="DtdVersion" type="xsd:string" use="optional"/>
		</xsd:complexType>
	</xsd:element>
	<xsd:complexType name="GSKSeries_Type">
		<xsd:sequence>
			<xsd:element name="TimeSeriesIdentification" type="ecc:IdentificationType"/>
			<xsd:element name="BusinessType" type="ecc:BusinessType"/>
			<xsd:element name="Area" type="ecc:AreaType"/>
			<xsd:element name="ManualGSK_Block" type="ManualGSK_Block_Type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="CountryGSK_Block" type="CountryGSK_Block_Type" minOccurs="0" maxOccurs="unbounded"/>
			<xsd:element name="AutoGSK_Block" type="AutoGSK_Block_Type" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManualGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType"/>
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType"/>
			<xsd:element name="ManualNodes" type="ManualNodes_Type" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ManualNodes_Type">
		<xsd:sequence>
			<xsd:element name="NodeName" type="ecc:IdentificationType"/>
			<xsd:element name="Factor" type="ecc:QuantityType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AutoGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType"/>
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType"/>
			<xsd:element name="AutoNodes" type="AutoNodes_Type" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AutoNodes_Type">
		<xsd:sequence>
			<xsd:element name="NodeName" type="ecc:IdentificationType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="CountryGSK_Block_Type">
		<xsd:sequence>
			<xsd:element name="GSK_Name" type="ecc:IdentificationType"/>
			<xsd:element name="TimeInterval" type="ecc:TimeIntervalType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="Reason_Type">
		<xsd:sequence>
			<xsd:element name="ReasonCode" type="ecc:ReasonCodeType"/>
			<xsd:element name="ReasonText" type="ecc:ReasonTextType" minOccurs="0" maxOccurs="unbounded"/>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== farao-community/ce-merging-server/src/test/resources/glskFix/20160728_GLSK_with_one_empty_glskSeries.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" DtdVersion="1" DtdRelease="0" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
	<DocumentIdentification v="17XTSO-CS------W-20160729-F112"/>
	<DocumentVersion v="1"/>
	<DocumentType v="Z02"/>
	<ProcessType v="Z02"/>
	<SenderIdentification v="XXXXXXXXXXXXX" codingScheme="A01"/>
	<SenderRole v="A36"/>
	<ReceiverIdentification v="YYYYYYYYYY" codingScheme="A01"/>
	<ReceiverRole v="A04"/>
	<CreationDateTime v="2017-10-30T09:27:21Z"/>
	<GSKTimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z"/>
	<Domain v="domain" codingScheme="A01"/>
	<GSKSeries>
		<TimeSeriesIdentification v="5"/>
		<BusinessType v="Z02" share="10"/>
		<Area v="area3" codingScheme="A01"/>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="3"/>
		<BusinessType v="Z05" share="70"/>
		<Area v="area1" codingScheme="A01"/>
		<AutoGSK_Block>
			<GSK_Name v="FR"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z"/>
			<AutoNodes>
				<NodeName v="FFR2AA2 "/>
			</AutoNodes>
		</AutoGSK_Block>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="4"/>
		<BusinessType v="Z02" share="100"/>
		<Area v="area2" codingScheme="A01"/>
		<AutoGSK_Block>
			<GSK_Name v="name2"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-28T23:00Z"/>
			<AutoNodes>
				<NodeName v="XXF1AA1 "/>
			</AutoNodes>
		</AutoGSK_Block>
		<AutoGSK_Block>
			<GSK_Name v="name2"/>
			<TimeInterval v="2016-07-28T23:00Z/2016-07-29T22:00Z"/>
			<AutoNodes>
				<NodeName v="XXF1AA1 "/>
			</AutoNodes>
			<AutoNodes>
				<NodeName v="XXF1AA2 "/>
			</AutoNodes>
		</AutoGSK_Block>
	</GSKSeries>
</GSKDocument>

=== farao-community/ce-merging-server/src/test/resources/glskFix/20160728_Alegro.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<GSKDocument xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" DtdVersion="1" DtdRelease="0" xsi:noNamespaceSchemaLocation="gsk-document.xsd">
	<DocumentIdentification v="XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"/>
	<DocumentVersion v="1"/>
	<DocumentType v="Z02"/>
	<ProcessType v="Z02"/>
	<SenderIdentification v="XXXXXXXXXXX" codingScheme="A01"/>
	<SenderRole v="A36"/>
	<ReceiverIdentification v="XXXXXXXXXXX" codingScheme="A01"/>
	<ReceiverRole v="A04"/>
	<CreationDateTime v="2017-10-30T09:27:21Z"/>
	<GSKTimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z"/>
	<Domain v="XXXXXXXXXXX" codingScheme="A01"/>
	<GSKSeries>
		<TimeSeriesIdentification v="2"/>
		<BusinessType v="Z02" share="30"/>
		<Area v="string" codingScheme="A01"/>
		<AutoGSK_Block>
			<GSK_Name v="XX"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z"/>
			<AutoNodes>
				<NodeName v="ABA1BB1 "/>
			</AutoNodes>
		</AutoGSK_Block>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="3"/>
		<BusinessType v="Z05" share="70"/>
		<Area v="string" codingScheme="A01"/>
		<AutoGSK_Block>
			<GSK_Name v="XX"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z"/>
			<AutoNodes>
				<NodeName v="ABA1BB2 "/>
			</AutoNodes>
		</AutoGSK_Block>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="4"/>
		<BusinessType v="Z02" share="100"/>
		<Area v="string2" codingScheme="A01"/>
		<AutoGSK_Block>
			<GSK_Name v="YY"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-28T23:00Z"/>
			<AutoNodes>
				<NodeName v="XXL1DD1 "/>
			</AutoNodes>
		</AutoGSK_Block>
		<AutoGSK_Block>
			<GSK_Name v="YY"/>
			<TimeInterval v="2016-07-28T23:00Z/2016-07-29T22:00Z"/>
			<AutoNodes>
				<NodeName v="XXL1DD1"/>
			</AutoNodes>
			<AutoNodes>
				<NodeName v="XXL1DD2"/>
			</AutoNodes>
		</AutoGSK_Block>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="17"/>
		<BusinessType share="100.000" v="Z02"/>
		<Area v="area1" codingScheme="A01"/>
		<ManualGSK_Block>
			<GSK_Name v="DE_ALEGrO"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z" />
			<ManualNodes>
				<NodeName v="TEST1"/>
				<Factor v="1"/>
			</ManualNodes>
		</ManualGSK_Block>
	</GSKSeries>
	<GSKSeries>
		<TimeSeriesIdentification v="18"/>
		<BusinessType share="100.000" v="Z02"/>
		<Area v="area2" codingScheme="A01"/>
		<ManualGSK_Block>
			<GSK_Name v="BE_ALEGrO"/>
			<TimeInterval v="2016-07-28T22:00Z/2016-07-29T22:00Z" />
			<ManualNodes>
				<NodeName v="TEST2"/>
				<Factor v="1"/>
			</ManualNodes>
		</ManualGSK_Block>
	</GSKSeries>
</GSKDocument>
